// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: protos/chat.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeChatService_SendMessage_FullMethodName               = "/RealtimeChatService/SendMessage"
	RealtimeChatService_GetUserFollowingFollowers_FullMethodName = "/RealtimeChatService/GetUserFollowingFollowers"
)

// RealtimeChatServiceClient is the client API for RealtimeChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealtimeChatServiceClient interface {
	SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	GetUserFollowingFollowers(ctx context.Context, in *GetUserFollowingFollowersRequest, opts ...grpc.CallOption) (*UserFollowingFollowersResponse, error)
}

type realtimeChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeChatServiceClient(cc grpc.ClientConnInterface) RealtimeChatServiceClient {
	return &realtimeChatServiceClient{cc}
}

func (c *realtimeChatServiceClient) SendMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, RealtimeChatService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realtimeChatServiceClient) GetUserFollowingFollowers(ctx context.Context, in *GetUserFollowingFollowersRequest, opts ...grpc.CallOption) (*UserFollowingFollowersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowingFollowersResponse)
	err := c.cc.Invoke(ctx, RealtimeChatService_GetUserFollowingFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealtimeChatServiceServer is the server API for RealtimeChatService service.
// All implementations must embed UnimplementedRealtimeChatServiceServer
// for forward compatibility.
type RealtimeChatServiceServer interface {
	SendMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	GetUserFollowingFollowers(context.Context, *GetUserFollowingFollowersRequest) (*UserFollowingFollowersResponse, error)
	mustEmbedUnimplementedRealtimeChatServiceServer()
}

// UnimplementedRealtimeChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeChatServiceServer struct{}

func (UnimplementedRealtimeChatServiceServer) SendMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedRealtimeChatServiceServer) GetUserFollowingFollowers(context.Context, *GetUserFollowingFollowersRequest) (*UserFollowingFollowersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserFollowingFollowers not implemented")
}
func (UnimplementedRealtimeChatServiceServer) mustEmbedUnimplementedRealtimeChatServiceServer() {}
func (UnimplementedRealtimeChatServiceServer) testEmbeddedByValue()                             {}

// UnsafeRealtimeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeChatServiceServer will
// result in compilation errors.
type UnsafeRealtimeChatServiceServer interface {
	mustEmbedUnimplementedRealtimeChatServiceServer()
}

func RegisterRealtimeChatServiceServer(s grpc.ServiceRegistrar, srv RealtimeChatServiceServer) {
	// If the following call panics, it indicates UnimplementedRealtimeChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeChatService_ServiceDesc, srv)
}

func _RealtimeChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeChatService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeChatServiceServer).SendMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealtimeChatService_GetUserFollowingFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserFollowingFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealtimeChatServiceServer).GetUserFollowingFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RealtimeChatService_GetUserFollowingFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealtimeChatServiceServer).GetUserFollowingFollowers(ctx, req.(*GetUserFollowingFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RealtimeChatService_ServiceDesc is the grpc.ServiceDesc for RealtimeChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RealtimeChatService",
	HandlerType: (*RealtimeChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _RealtimeChatService_SendMessage_Handler,
		},
		{
			MethodName: "GetUserFollowingFollowers",
			Handler:    _RealtimeChatService_GetUserFollowingFollowers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/chat.proto",
}
